---
name: latex

on:
  push:
    paths:
      - .github/workflows/latex.yaml
      - '**.tex'
      - latexmk

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
